
language: dart
dist: xenial
addons:  # installer des packages supplementaire sur le sys OS
  apt:
    packages:
      - lib32stdc++6
install:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor #aulieu de pub get
  - gem install coveralls-lcov # install coveralls-lcov pour installer les combinaison
# script:
#   - ./flutter/bin/flutter test --coverage #generer un rapport de couverture de code
# after_success:  #pour envoyer le rapport de couverture de test
#   - coveralls-lcov coverage/lcov.info
#   - ./flutter/bin/flutter test  
# after_success:
#   -coveralls-lcov coverage/lcov.info #pour envoyer le rapport de couverture de test
cache:
  directories:
    - $HOME/.pub-cache #pour indiquer a travis de mettre en cache le contenu du cache de dart par defaut pour que flutter puisse installer rapidement les dependences de lapp

