name: Dart CI
 
on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
     
    container:
      image:  google/dart:latest
     
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: flutter pub get #./flutter/bin/flutter doctor #
    - name: Run tests
      run: flutter pub run test #./flutter/bin/flutter test #
    - name: Code Coverage
      run: pub run test_coverage #./flutter/bin/flutter test --coverage #
    - name: Upload coverage to Codecov 
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: coverage/lcov.info
