name: coran
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versAAioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  sqflite: ^1.2.0
  path_provider: ^1.5.1
  shared_preferences: ^0.5.6
  http: ^0.12.0+3
  path: ^1.6.4
  flutter_share: ^1.0.2+1
  audioplayer: 0.8.1
  audioplayer_web: 0.7.1
  audioplayers: ^0.13.7
  share: '>=0.6.2+3 <2.0.0'
  arabic_words: ^0.1.22
  google_fonts_arabic: ^1.1.7
  google_fonts: ^1.0.0
  onesignal_flutter: ^2.4.1
  intl: ^0.16.1
  draggable_scrollbar: ^0.0.4
  flutter_pdfview: ^1.0.1
  flutter_plugin_pdf_viewer: ^1.0.7
  scrollable_positioned_list: ^0.1.5 
  provider: ^3.1.0
  flutter_launcher_icons: "^0.7.3"
  test: ^1.15.0
  test_coverage: ^0.4.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/homme.webp"
dev_dependencies:
  flutter_test:
    sdk: flutter  


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/invocations/
    - assets/icons/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    # - family: amiri
    #   fonts:
    #      - asset: assets/fonts/ArbFONTS-Amiri-Bold.ttf
    # - family: amiriquran
    #   fonts:
    #      - asset: assets/fonts/amiri_quran.ttf
    # - family: amiriregquran
    #   fonts:
    #      - asset: assets/fonts/Amiri_Quran_Regular.ttf
    - family: noorehidayat
      fonts:
         - asset: assets/fonts/noorehidayat.ttf
    - family: mequran
      fonts:
         - asset: assets/fonts/me_quran.ttf
    # - family: standquran
    #   fonts:
    #      - asset: assets/fonts/qur_std.ttf
    # - family: madina
    #   fonts:
    #      - asset: assets/fonts/maddina.ttf
    # - family: mcsgf
    #   fonts:
    #      - asset: assets/fonts/mcs_gf.ttf
    # - family: mcsquran
    #   fonts:
    #      - asset: assets/fonts/Mcs-Quran.ttf
    # - family: mcs
    #   fonts:
    #      - asset: assets/fonts/MCS-normal.ttf
    # - family: akhand
    #   fonts:
    #      - asset: assets/fonts/AkhandArabic.ttf
    # - family: tajawal
    #   fonts:
    #      - asset: assets/fonts/Tajawal-Regular.ttf
    #      - asset: assets/fonts/Tajawal-Bold.ttf
    #        weight: 600
    #      - asset: assets/fonts/Tajawal-Bold.ttf
    #        weight: 700
    #      - asset: assets/fonts/Tajawal-ExtraBold.ttf
    #        weight: 800
    #      - asset: assets/fonts/Tajawal-Medium.ttf
    #        weight: 500
    #      - asset: assets/fonts/Tajawal-Light.ttf
    #        weight: 300
    #      - asset: assets/fonts/Tajawal-ExtraLight.ttf
    #        weight: 200
    # - family: khebrat
    #   fonts:
    #      - asset: assets/fonts/Khebrat-Musamim-New.ttf
    # - family:  LabIcons
    #   fonts:
    #      - asset: assets/icons/LabIcons.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
