name: coran
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  sqflite: ^1.2.0
  path_provider: ^1.5.1
  flutter_share: ^1.0.2+1
  audioplayer: 0.8.1
  audioplayer_web: 0.7.1
  share: '>=0.6.2+3 <2.0.0'
  arabic_words: ^0.1.22
  google_fonts: ^1.0.0
  intl: ^0.16.1
  flutter_plugin_pdf_viewer: ^1.0.7
  scrollable_positioned_list: ^0.1.5 
  # provider: ^3.1.0
  flutter_launcher_icons: "^0.7.3"
  # test: ^1.15.0
  test_coverage: ^0.4.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/myicon.webp"
dev_dependencies:
  flutter_test:
    sdk: flutter  
executables:
  codecov:
  generate_coverage:

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/invocations/
    - assets/icons/
  fonts:
    
    - family: noorehidayat
      fonts:
         - asset: assets/fonts/noorehidayat.ttf
    - family: mequran
      fonts:
         - asset: assets/fonts/me_quran.ttf
