import 'Alljiza.dart';

class MesAjiza {
  String numero;
  Ajiza ajiza;
  String nbaya;
  int hizb;
  String avanthizb;
  MesAjiza({this.numero, this.nbaya, this.ajiza, this.hizb, this.avanthizb});
}

List<MesAjiza> mesAjiza = [
  MesAjiza(
    numero: "Xaaj'1",
    nbaya: 'Laaya 1',
    ajiza: fatiha,
    hizb: 1,
  ),
  MesAjiza(
      numero: "Xaaj'1",
      nbaya: 'Laaya 26',
      ajiza: baquara26,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'1",
      nbaya: 'Laaya 44',
      ajiza: baquara44,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'1",
      nbaya: 'Laaya 60',
      ajiza: baquara60,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'1", nbaya: 'Laaya  75', ajiza: baquara75, hizb: 2),
  MesAjiza(
      numero: "Xaaj'1",
      nbaya: ' Laaya 92',
      ajiza: baquara92,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'1",
      nbaya: 'Laaya 106',
      ajiza: baquara106,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'1",
      nbaya: 'Laaya  124',
      ajiza: baquara124,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'2", nbaya: 'Laaya 142', ajiza: baquara142, hizb: 3),
  MesAjiza(
      numero: "Xaaj'2",
      nbaya: 'Laaya 158',
      ajiza: baquara158,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'2",
      nbaya: 'Laaya 177',
      ajiza: baquara177,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'2",
      nbaya: 'Laaya 189',
      ajiza: baquara189,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'2", nbaya: 'Laaya 203', ajiza: baquara203, hizb: 4),
  MesAjiza(
      numero: "Xaaj'2",
      nbaya: 'Laaya 219',
      ajiza: baquara219,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'2",
      nbaya: 'Laaya 233',
      ajiza: baquara233,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'2",
      nbaya: 'Laaya 243',
      ajiza: baquara243,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'3", nbaya: 'Laaya 253', ajiza: baquara253, hizb: 5),
  MesAjiza(
      numero: "Xaaj'3",
      nbaya: 'Laaya 263',
      ajiza: baquara263,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'3",
      nbaya: 'Laaya 272',
      ajiza: baquara272,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'3",
      nbaya: 'Laaya 283',
      ajiza: baquara283,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'3", nbaya: 'Laaya 15', ajiza: imran15, hizb: 6),
  MesAjiza(
      numero: "Xaaj'3",
      nbaya: 'Laaya 33',
      ajiza: imran33,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'3",
      nbaya: 'Laaya 52',
      ajiza: imran52,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'3",
      nbaya: 'Laaya 75',
      ajiza: imran75,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'4", nbaya: 'Laaya 93', ajiza: imran93, hizb: 7),
  MesAjiza(
      numero: "Xaaj'4",
      nbaya: 'Laaya 113',
      ajiza: imran113,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'4",
      nbaya: 'Laaya 133',
      ajiza: imran133,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'4",
      nbaya: 'Laaya 153',
      ajiza: imran153,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'4", nbaya: 'Laaya 171', ajiza: imran171, hizb: 8),
  MesAjiza(
      numero: "Xaaj'4",
      nbaya: 'Laaya 186',
      ajiza: imran186,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'4",
      nbaya: 'Laaya 1',
      ajiza: nisa1,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'4",
      nbaya: 'Laaya 12',
      ajiza: nisa12,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'5", nbaya: 'Laaya 24', ajiza: nisa24, hizb: 9),
  MesAjiza(
      numero: "Xaaj'5",
      nbaya: 'Laaya 36',
      ajiza: nisa36,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'5",
      nbaya: 'Laaya 58',
      ajiza: nisa58,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'5",
      nbaya: 'Laaya 74',
      ajiza: nisa74,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'5", nbaya: 'Laaya 88', ajiza: nisa88, hizb: 10),
  MesAjiza(
      numero: "Xaaj'5",
      nbaya: 'Laaya 100',
      ajiza: nisa100,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'5",
      nbaya: 'Laaya 114',
      ajiza: nisa114,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'5",
      nbaya: 'Laaya 135',
      ajiza: nisa135,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'6", nbaya: 'Laaya 148', ajiza: nisa148, hizb: 11),
  MesAjiza(
      numero: "Xaaj'6",
      nbaya: 'Laaya 163',
      ajiza: nisa163,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'6",
      nbaya: 'Laaya 1',
      ajiza: maida1,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'6",
      nbaya: 'Laaya 12',
      ajiza: maida12,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'6", nbaya: 'Laaya 27', ajiza: maida27, hizb: 12),
  MesAjiza(
      numero: "Xaaj'6",
      nbaya: 'Laaya 41',
      ajiza: maida41,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'6",
      nbaya: 'Laaya 51',
      ajiza: maida51,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'6",
      nbaya: 'Laaya 67',
      ajiza: maida67,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'7", nbaya: 'Laaya 82', ajiza: maida82, hizb: 13),
  MesAjiza(
      numero: "Xaaj'7",
      nbaya: 'Laaya 97',
      ajiza: maida97,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'7",
      nbaya: 'Laaya 109',
      ajiza: maida109,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'7",
      nbaya: 'Laaya 13',
      ajiza: anam13,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'7", nbaya: 'Laaya 36', ajiza: anam36, hizb: 14),
  MesAjiza(
      numero: "Xaaj'7",
      nbaya: 'Laaya 59',
      ajiza: anam59,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'7",
      nbaya: 'Laaya 74',
      ajiza: anam74,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'7",
      nbaya: 'Laaya 95',
      ajiza: anam95,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'8", nbaya: 'Laaya 111', ajiza: anam111, hizb: 15),
  MesAjiza(
      numero: "Xaaj'8",
      nbaya: 'Laaya 127',
      ajiza: anam127,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'8",
      nbaya: 'Laaya 141',
      ajiza: anam141,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'8",
      nbaya: 'Laaya 151',
      ajiza: anam151,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'8", nbaya: 'Laaya 1', ajiza: araf1, hizb: 16),
  MesAjiza(
      numero: "Xaaj'8",
      nbaya: 'Laaya 31',
      ajiza: araf31,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'8",
      nbaya: 'Laaya 47',
      ajiza: araf47,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'8",
      nbaya: 'Laaya 65',
      ajiza: araf65,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'9", nbaya: 'Laaya 88', ajiza: araf88, hizb: 17),
  MesAjiza(
      numero: "Xaaj'9",
      nbaya: 'Laaya 117',
      ajiza: araf117,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'9",
      nbaya: 'Laaya 142',
      ajiza: araf142,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'9",
      nbaya: 'Laaya 156',
      ajiza: araf156,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'9", nbaya: 'Laaya 171', ajiza: araf171, hizb: 18),
  MesAjiza(
      numero: "Xaaj'9",
      nbaya: 'Laaya 189',
      ajiza: araf189,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'9",
      nbaya: 'Laaya 1',
      ajiza: anfal1,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'9",
      nbaya: 'Laaya 22',
      ajiza: anfal22,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'10", nbaya: 'Laaya 41', ajiza: anfal41, hizb: 19),
  MesAjiza(
      numero: "Xaaj'10",
      nbaya: 'Laaya 61',
      ajiza: anfal61,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'10",
      nbaya: 'Laaya 1',
      ajiza: tawbah1,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'10",
      nbaya: 'Laaya 19',
      ajiza: tawbah19,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'10", nbaya: 'Laaya 34', ajiza: tawbah34, hizb: 20),
  MesAjiza(
      numero: "Xaaj'10",
      nbaya: 'Laaya 46',
      ajiza: tawbah46,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'10",
      nbaya: 'Laaya 60',
      ajiza: tawbah60,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'10",
      nbaya: 'Laaya 75',
      ajiza: tawbah75,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'11", nbaya: 'Laaya 93', ajiza: tawbah93, hizb: 21),
  MesAjiza(
      numero: "Xaaj'11",
      nbaya: 'Laaya 111',
      ajiza: tawbah111,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'11",
      nbaya: 'Laaya 122',
      ajiza: tawbah122,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'11",
      nbaya: 'Laaya 11',
      ajiza: yunus11,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'10", nbaya: 'Laaya 26', ajiza: yunus26, hizb: 22),
  MesAjiza(
      numero: "Xaaj'11",
      nbaya: 'Laaya 53',
      ajiza: yunus53,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'11",
      nbaya: 'Laaya 71',
      ajiza: yunus71,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'11",
      nbaya: 'Laaya 90',
      ajiza: yunus90,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'12", nbaya: 'Laaya 6', ajiza: hud6, hizb: 23),
  MesAjiza(
      numero: "Xaaj'12",
      nbaya: 'Laaya 24',
      ajiza: hud24,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'12",
      nbaya: 'Laaya 41',
      ajiza: hud41,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'12",
      nbaya: 'Laaya 61',
      ajiza: hud61,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'12", nbaya: 'Laaya 84', ajiza: hud84, hizb: 24),
  MesAjiza(
      numero: "Xaaj'12",
      nbaya: 'Laaya 108',
      ajiza: hud108,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'12",
      nbaya: 'Laaya 7',
      ajiza: yussuf7,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'12",
      nbaya: 'Laaya 30',
      ajiza: yussuf30,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'13", nbaya: 'Laaya 53', ajiza: yussuf53, hizb: 25),
  MesAjiza(
      numero: "Xaaj'13",
      nbaya: 'Laaya 77',
      ajiza: yussuf77,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'13",
      nbaya: 'Laaya 101',
      ajiza: yussuf101,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'13",
      nbaya: 'Laaya 5',
      ajiza: arrad5,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'13", nbaya: 'Laaya 19', ajiza: arrad19, hizb: 19),
  MesAjiza(
      numero: "Xaaj'13",
      nbaya: 'Laaya 35',
      ajiza: arrad35,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'13",
      nbaya: 'Laaya 10',
      ajiza: ibrahim10,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'13",
      nbaya: 'Laaya 28',
      ajiza: ibrahim28,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'14", nbaya: 'Laaya 1', ajiza: alhijr1, hizb: 27),
  MesAjiza(
      numero: "Xaaj'14",
      nbaya: 'Laaya 49',
      ajiza: alhijr49,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'14",
      nbaya: 'Laaya 1',
      ajiza: annahl1,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'14",
      nbaya: 'Laaya 30',
      ajiza: annahl30,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'14", nbaya: 'Laaya 51', ajiza: annahl51, hizb: 28),
  MesAjiza(
      numero: "Xaaj'14",
      nbaya: 'Laaya 75',
      ajiza: annahl75,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'14",
      nbaya: 'Laaya 90',
      ajiza: annahl90,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'14",
      nbaya: 'Laaya 111',
      ajiza: annahl111,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'15", nbaya: 'Laaya 1', ajiza: alisra1, hizb: 29),
  MesAjiza(
      numero: "Xaaj'15",
      nbaya: 'Laaya 23',
      ajiza: alisra23,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'15",
      nbaya: 'Laaya 50',
      ajiza: alisra50,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'15",
      nbaya: 'Laaya 70',
      ajiza: alisra70,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'15", nbaya: 'Laaya 99', ajiza: alisra99, hizb: 30),
  MesAjiza(
      numero: "Xaaj'15",
      nbaya: 'Laaya 17',
      ajiza: alkahf17,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'15",
      nbaya: 'Laaya 32',
      ajiza: alkahf32,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'15",
      nbaya: 'Laaya 51',
      ajiza: alkahf51,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'16", nbaya: 'Laaya 75', ajiza: alkahf75, hizb: 31),
  MesAjiza(
      numero: "Xaaj'16",
      nbaya: 'Laaya 99',
      ajiza: alkahf99,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'16",
      nbaya: 'Laaya 22',
      ajiza: maryam22,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'16",
      nbaya: 'Laaya 59',
      ajiza: maryam59,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'16", nbaya: 'Laaya 1', ajiza: taha1, hizb: 32),
  MesAjiza(
      numero: "Xaaj'16",
      nbaya: 'Laaya 55',
      ajiza: taha55,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'16",
      nbaya: 'Laaya 83',
      ajiza: taha83,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'16",
      nbaya: 'Laaya 111',
      ajiza: taha111,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(
      numero: "Xaaj'17",
      nbaya: 'Laaya 29',
      ajiza: alnabiya29,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'17",
      nbaya: 'Laaya 51',
      ajiza: alnabiya51,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'17",
      nbaya: 'Laaya 83',
      ajiza: alnabiya83,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'17", nbaya: 'Laaya 1', ajiza: alHajj1, hizb: 34),
  MesAjiza(
      numero: "Xaaj'17",
      nbaya: 'Laaya 19',
      ajiza: alHajj19,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'17",
      nbaya: 'Laaya 38',
      ajiza: alHajj38,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'17",
      nbaya: 'Laaya 60',
      ajiza: alHajj60,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'18", nbaya: 'Laaya 1', ajiza: muminum1, hizb: 35),
  MesAjiza(
      numero: "Xaaj'18",
      nbaya: 'Laaya 36',
      ajiza: muminum36,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'18",
      nbaya: 'Laaya 75',
      ajiza: muminum75,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'18",
      nbaya: 'Laaya 1',
      ajiza: annur1,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'18", nbaya: 'Laaya 21', ajiza: annur21, hizb: 36),
  MesAjiza(
      numero: "Xaaj'18",
      nbaya: 'Laaya 35',
      ajiza: annur35,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'18",
      nbaya: 'Laaya 53',
      ajiza: annur53,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'18",
      nbaya: 'Laaya 1',
      ajiza: furqan1,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'19", nbaya: 'Laaya 21', ajiza: furqan21, hizb: 37),
  MesAjiza(
      numero: "Xaaj'19",
      nbaya: 'Laaya 53',
      ajiza: furqan53,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'19",
      nbaya: 'Laaya 1',
      ajiza: ashura1,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'19",
      nbaya: 'Laaya 52',
      ajiza: ashura52,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'19", nbaya: 'Laaya 111', ajiza: ashura111, hizb: 38),
  MesAjiza(
      numero: "Xaaj'19",
      nbaya: 'Laaya 181',
      ajiza: ashura181,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'19",
      nbaya: 'Laaya 1',
      ajiza: annaml1,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'19",
      nbaya: 'Laaya 27',
      ajiza: annaml27,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'20", nbaya: 'Laaya 56', ajiza: annaml56, hizb: 39),
  MesAjiza(
      numero: "Xaaj'20",
      nbaya: 'Laaya 82',
      ajiza: annaml82,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'20",
      nbaya: 'Laaya 12',
      ajiza: alqasas12,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'20",
      nbaya: 'Laaya 29',
      ajiza: alqasas29,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'20", nbaya: 'Laaya 51', ajiza: alqasas51, hizb: 40),
  MesAjiza(
      numero: "Xaaj'20",
      nbaya: 'Laaya 76',
      ajiza: alqasas76,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'20",
      nbaya: 'Laaya 1',
      ajiza: ankatub1,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'20",
      nbaya: 'Laaya 26',
      ajiza: ankatub26,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'20", nbaya: 'Laaya 46', ajiza: ankatub46, hizb: 41),
  MesAjiza(
      numero: "Xaaj'21",
      nbaya: 'Laaya 1',
      ajiza: arum1,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'21",
      nbaya: 'Laaya 31',
      ajiza: arum31,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'21",
      nbaya: 'Laaya 54',
      ajiza: arum54,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'21", nbaya: 'Laaya 22', ajiza: luqman22, hizb: 42),
  MesAjiza(
      numero: "Xaaj'21",
      nbaya: 'Laaya 11',
      ajiza: aasajda11,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'21",
      nbaya: 'Laaya 1',
      ajiza: alhazab1,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'21",
      nbaya: 'Laaya 18',
      ajiza: alhazab18,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'22", nbaya: 'Laaya 31', ajiza: alhazab31, hizb: 43),
  MesAjiza(
      numero: "Xaaj'22",
      nbaya: 'Laaya 51',
      ajiza: alhazab51,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'22",
      nbaya: 'Laaya 60',
      ajiza: alhazab60,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'22",
      nbaya: 'Laaya 10',
      ajiza: saba10,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'22", nbaya: 'Laaya 24', ajiza: saba24, hizb: 44),
  MesAjiza(
      numero: "Xaaj'22",
      nbaya: 'Laaya 46',
      ajiza: saba46,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'22",
      nbaya: 'Laaya 15',
      ajiza: fatir15,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'22",
      nbaya: 'Laaya 41',
      ajiza: fatir41,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'23", nbaya: 'Laaya 28', ajiza: yassin28, hizb: 45),
  MesAjiza(
      numero: "Xaaj'23",
      nbaya: 'Laaya 60',
      ajiza: yassin60,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'23",
      nbaya: 'Laaya 22',
      ajiza: assafat22,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'23",
      nbaya: 'Laaya 83',
      ajiza: assafat83,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'23", nbaya: 'Laaya 145', ajiza: assafat145, hizb: 46),
  MesAjiza(
      numero: "Xaaj'23",
      nbaya: 'Laaya 21',
      ajiza: sad21,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'23",
      nbaya: 'Laaya 52',
      ajiza: sad52,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'23",
      nbaya: 'Laaya 8',
      ajiza: azzumar8,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'24", nbaya: 'Laaya 32', ajiza: azzumar32, hizb: 47),
  MesAjiza(
      numero: "Xaaj'24",
      nbaya: 'Laaya 53',
      ajiza: azzumar53,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'24",
      nbaya: 'Laaya 1',
      ajiza: ghafir1,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'24",
      nbaya: 'Laaya 21',
      ajiza: ghafir21,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'24", nbaya: 'Laaya 41', ajiza: ghafir41, hizb: 48),
  MesAjiza(
      numero: "Xaaj'24",
      nbaya: 'Laaya 66',
      ajiza: ghafir66,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'24",
      nbaya: 'Laaya 9',
      ajiza: fussila9,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'24",
      nbaya: 'Laaya 25',
      ajiza: fussila25,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'25", nbaya: 'Laaya 47', ajiza: fussila47, hizb: 49),
  MesAjiza(
      numero: "Xaaj'25",
      nbaya: 'Laaya 13',
      ajiza: ashshura13,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'25",
      nbaya: 'Laaya 27',
      ajiza: ashshura27,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'25",
      nbaya: 'Laaya 51',
      ajiza: ashshura51,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'25", nbaya: 'Laaya 24', ajiza: azukhruf24, hizb: 50),
  MesAjiza(
      numero: "Xaaj'25",
      nbaya: 'Laaya 57',
      ajiza: azukhruf57,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'25",
      nbaya: 'Laaya 17',
      ajiza: addukhan17,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'25",
      nbaya: 'Laaya 12',
      ajiza: aljathiya12,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'26", nbaya: 'Laaya 1', ajiza: alahqaf1, hizb: 51),
  MesAjiza(
      numero: "Xaaj'26",
      nbaya: 'Laaya 21',
      ajiza: alahqaf21,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'26",
      nbaya: 'Laaya 10',
      ajiza: mouhamed10,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'26",
      nbaya: 'Laaya 33',
      ajiza: mouhamed33,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'26", nbaya: 'Laaya 18', ajiza: alfath18, hizb: 52),
  MesAjiza(
      numero: "Xaaj'26",
      nbaya: 'Laaya 1',
      ajiza: alhujurat1,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'26",
      nbaya: 'Laaya 14',
      ajiza: alhujurat14,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'26",
      nbaya: 'Laaya 27',
      ajiza: qaf27,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'27", nbaya: 'Laaya 31', ajiza: adhariyat31, hizb: 53),
  MesAjiza(
      numero: "Xaaj'27",
      nbaya: 'Laaya 24',
      ajiza: attur24,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'27",
      nbaya: 'Laaya 26',
      ajiza: annajm26,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'27",
      nbaya: 'Laaya 9',
      ajiza: alqamar9,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'27", nbaya: 'Laaya 1', ajiza: arahman1, hizb: 54),
  MesAjiza(
      numero: "Xaaj'27",
      nbaya: 'Laaya 1',
      ajiza: alwaqiah1,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'27",
      nbaya: 'Laaya 75',
      ajiza: alwaqiah75,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'27",
      nbaya: 'Laaya 16',
      ajiza: alhadid16,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'28", nbaya: 'Laaya 1', ajiza: almujadila1, hizb: 55),
  MesAjiza(
      numero: "Xaaj'28",
      nbaya: 'Laaya 14',
      ajiza: almujadila14,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'28",
      nbaya: 'Laaya 11',
      ajiza: alhashr11,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'28",
      nbaya: 'Laaya 7',
      ajiza: almumtaHana7,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'28", nbaya: 'Laaya 1', ajiza: aljuma1, hizb: 56),
  MesAjiza(
      numero: "Xaaj'28",
      nbaya: 'Laaya 4',
      ajiza: almunafiqun4,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'28",
      nbaya: 'Laaya 1',
      ajiza: attalaq1,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'28",
      nbaya: 'Laaya 1',
      ajiza: attahrim1,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'29", nbaya: 'Laaya 1', ajiza: almulk1, hizb: 57),
  MesAjiza(
      numero: "Xaaj'29",
      nbaya: 'Laaya 1',
      ajiza: alqalam1,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'29",
      nbaya: 'Laaya 1',
      ajiza: alhaqqah1,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'29",
      nbaya: 'Laaya 19',
      ajiza: almarij19,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'29", nbaya: 'Laaya 1', ajiza: aljinn1, hizb: 58),
  MesAjiza(
      numero: "Xaaj'29",
      nbaya: 'Laaya 20',
      ajiza: almuzzammil20,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'29",
      nbaya: 'Laaya 1',
      ajiza: alqiyamah1,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'29",
      nbaya: 'Laaya 19',
      ajiza: alinsan19,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'30", nbaya: 'Laaya 1', ajiza: annaba1, hizb: 59),
  MesAjiza(
      numero: "Xaaj'30",
      nbaya: 'Laaya 1',
      ajiza: abassa1,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'30",
      nbaya: 'Laaya 1',
      ajiza: alinfitar1,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'30",
      nbaya: 'Laaya 1',
      ajiza: alinshiqaq1,
      hizb: 0,
      avanthizb: '3/4'),
  MesAjiza(numero: "Xaaj'30", nbaya: 'Laaya 1', ajiza: alala1, hizb: 60),
  MesAjiza(
      numero: "Xaaj'30",
      nbaya: 'Laaya 1',
      ajiza: albalad1,
      hizb: 0,
      avanthizb: '1/4'),
  MesAjiza(
      numero: "Xaaj'30",
      nbaya: 'Laaya 1',
      ajiza: alsharh1,
      hizb: 0,
      avanthizb: '2/4'),
  MesAjiza(
      numero: "Xaaj'30",
      nbaya: 'Laaya 9',
      ajiza: aladiyat9,
      hizb: 0,
      avanthizb: '3/4'),
];
